config/routes.rb
Rails.application.routes.draw do

  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to: "homes#top"
  
    # customer
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    patch 'customers/withdraw_update' => 'customers#withdraw_update', as: 'withdraw_update'
  
    # item
    resources :items, only: [:index, :show]
  
    # cart_item
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'delete_all'
      end
    end
  
    # address
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
    # order
    resources :orders, only: [:index, :new, :create, :show] do
      collection do
        post 'check', to: 'orders#check', as: 'check'
        get 'complete', to: 'orders#complete', as: 'complete'
      end
    end
  end

  




  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  get 'admin' => 'admin/homes#top', as: 'admin'

  namespace :admin do
    resources :customers, only: [:index,:show, :edit,:update]
    resources :genres, only: [:index,:create, :edit,:update]
    resources :items,only: [:new,:index,:create, :edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :order_details, only: [:update]
  end


    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :admin, only: [:index,:show, :edit,:update]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :oder_details, dependent: :destroy
  belongs_to :genre
  
  has_one_attached :image
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 0, message: "は0以上の数値を入力してください" }


  def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/sample1.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def self.recommended
    recommends = []
    active_genres = Genre.only_active.includes(:items)
    active_genres.each do |genre|
      item = genre.items.last
      recommends << item if item
    end
    recommends
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!
    def index
        if params[:search] == "perfect_match"
          @items = Item.where("name LIKE ?", "#{params[:word]}")
        elsif params[:search] == "forward_match"
          @items = Item.where("name LIKE ?", "#{params[:word]}%")
        elsif params[:search] == "backward_match"
          @items = Item.where("name LIKE ?", "%#{params[:word]}")
        elsif params[:search] == "partial_match"
          @items = Item.where("name LIKE ?", "%#{params[:word]}%")
          
        else
          @items = Item.all
        end
        
    end

    def new
        @item=Item.new
        @genre=Genre.all
    end

    def create
        @item = Item.new(item_params)
        if @item.save
          flash[:success] = "登録成功"
          redirect_to admin_items_path
        else
            @genre=Genre.all
            render :new
        end
    end

    def edit
      @item=Item.find(params[:id])
      @genre = Genre.all
    end
  
    def update
      @item = Item.find(params[:id])
      if @item.update(item_params)
        flash[:success] = "商品情報が更新されました"
        redirect_to admin_items_path
      else
        flash.now[:error] = "更新に失敗しました"
        @genre= Genre.all
        render :edit
      end
    end

    def item_params
        params.require(:item).permit(:image,:name, :introduction,:price,:is_deleted,:genre_id)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<%= render 'admin/shared/error_messages', resource: @item %>

<div class="container mt-4">
  <h1 class="my-4 text-center">商品編集</h1>

  <%= form_with model: @item, url: admin_item_path(@item), method: :patch, class: "form" do |f| %>
    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :image, "商品画像", class: "form-label" %>
        <%= f.file_field :image, class: "form-control", accept: "image/*" %>
      </div>

      <div class="col-md-6">
        <%= f.label :name, "タイトル", class: "form-label" %>
        <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "タイトル" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :introduction, "説明文", class: "form-label" %>
        <%= f.text_field :introduction, class: "form-control", placeholder: "説明文" %>
      </div>

      <div class="col-md-6 genre_field">
        <%= f.label :genre_id, "ジャンル", class: "form-label" %><br>
        <%= f.collection_select :genre_id, @genre, :id, :name, { prompt: "ジャンル名" }, class: "form-select" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :price, "値段", class: "form-label" %>
        <%= f.text_field :price, class: "form-control", placeholder: "値段" %>
      </div>

      <div class="col-md-6 is_deleted_field">
        <label class="form-label">販売ステータス</label>
        <div class="form-check">
          <%= f.radio_button :is_deleted, "false", class: "form-check-input" %>
          <%= f.label :is_deleted, "販売中", value: "false", class: "form-check-label" %>
        </div>
        <div class="form-check">
          <%= f.radio_button :is_deleted, "true", class: "form-check-input" %>
          <%= f.label :is_deleted, "販売停止中", value: "true", class: "form-check-label" %>
        </div>
      </div>
    </div>

    <div class="text-center mt-4">
      <%= f.submit '更新', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<h1 class="my-4 text-center">商品一覧 (admin)</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead class="thead-light">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>販売ステータス</th>
        <th>アクション</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.name %></td>
          <td><%= number_to_currency(item.price, unit: "¥", format: "%u%n") %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_deleted %>
              <span class="badge bg-danger">停止中</span>
            <% else %>
              <span class="badge bg-success">販売中</span>
            <% end %>
          </td>
          <td>
            <%= link_to '編集', edit_admin_item_path(item), class: "btn btn-sm btn-secondary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="text-center mt-4">
  <%= link_to "商品新規登録", new_admin_item_path, class: "btn btn-primary" %>
</div>

app/views/admin/items/new.html.erb
<%= render 'admin/shared/error_messages', resource: @item %><!-- 部分テンプレートファイル -->

<div class="container mt-4">
  <h1 class="my-4 text-center">商品登録</h1>

  <%= form_with model: @item, url: admin_items_path, class: "form" do |f| %>
    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :image, "商品画像", class: "form-label" %>
        <%= f.file_field :image, class: "form-control", accept: "image/*" %>
      </div>

      <div class="col-md-6">
        <%= f.label :name, "タイトル", class: "form-label" %>
        <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "タイトル" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :introduction, "説明文", class: "form-label" %>
        <%= f.text_field :introduction, class: "form-control", placeholder: "説明文", style: "height: calc(2.25rem + 2px);" %>
      </div>

      <div class="col-md-6 genre_field">
        <%= f.label :genre_id, "ジャンル", class: "form-label" %><br>
        <%= f.collection_select :genre_id, @genre, :id, :name, { prompt: "ジャンル名" }, class: "form-select", style: "height: calc(2.25rem + 2px);" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <%= f.label :price, "値段", class: "form-label" %>
        <%= f.text_field :price, class: "form-control", placeholder: "値段" %>
      </div>

      <div class="col-md-6 is_deleted_field">
        <label class="form-label">販売ステータス</label>
        <div class="form-check">
          <%= f.radio_button :is_deleted, "false", class: "form-check-input" %>
          <%= f.label :is_deleted, "販売中", value: "false", class: "form-check-label" %>
        </div>
        <div class="form-check">
          <%= f.radio_button :is_deleted, "true", class: "form-check-input" %>
          <%= f.label :is_deleted, "販売停止中", value: "true", class: "form-check-label" %>
        </div>
      </div>
    </div>

    <div class="text-center mt-4">
      <%= f.submit '追加', class: "btn btn-primary" %>
    </div>
  <% end %>
</div>