config/routes.rb
Rails.application.routes.draw do

  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  scope module: :public do
    root to: "homes#top"
  
    # customer
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_customer'
    patch 'customers/information' => 'customers#update', as: 'update_customer'
    get 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    patch 'customers/withdraw_update' => 'customers#withdraw_update', as: 'withdraw_update'
  
    # item
    resources :items, only: [:index, :show]
  
    # cart_item
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all', as: 'delete_all'
      end
    end
  
    # address
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  
    # order
    resources :orders, only: [:index, :new, :create, :show] do
      collection do
        post 'check', to: 'orders#check', as: 'check'
        get 'complete', to: 'orders#complete', as: 'complete'
      end
    end
  end

  




  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  get 'admin' => 'admin/homes#top', as: 'admin'

  namespace :admin do
    resources :customers, only: [:index,:show, :edit,:update]
    resources :genres, only: [:index,:create, :edit,:update]
    resources :items,only: [:new,:index,:create, :edit,:update]
    resources :orders, only: [:index,:show,:update]
    resources :order_details, only: [:update]
  end


    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :admin, only: [:index,:show, :edit,:update]
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true,uniqueness: true
  
  has_many :items
  scope :only_active, -> { where(is_deleted: false) }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre=Genre.new
    @genres=Genre.all
      
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:success] = "投稿成功"
      redirect_to admin_genres_path
    else
      @genres=Genre.all
      render :new
    end
  end
  
  def edit
    @genre=Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    if @genre.save
      flash[:success] = "編集成功"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
    
    
  private #createアクションの内部でのみ使用可能
	def genre_params
	    params.require(:genre).permit(:name)# ストロングパラメータ
	end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<% if @genre.errors.any? %> 
  <div class="alert alert-danger">
    <h4 class="alert-heading"><%= @genre.errors.count %> errors occurred</h4>
    <ul>
      <% @genre.errors.full_messages.each do |message| %> 
        <li><%= message %></li>　
      <% end %>
    </ul>
  </div>
<% end %>

<h1 class="mb-4">ジャンル編集</h1>

<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<%= form_with model: @genre, url: admin_genre_path(@genre.id), class: "form" do |f| %>

  <div class="form-group" style="max-width: 400px;">
    <label for="genre_name">ジャンル名</label>
    <%= f.text_field :name, class: "form-control", id: "genre_name", autofocus: true, placeholder: "ジャンル名" %>
  </div>

  <br>

  <%= f.submit '編集', class: "btn btn-primary" %>

<% end %>

app/views/admin/genres/index.html.erb
<% if @genre.errors.any? %> 
  <div class="alert alert-danger text-center" style="max-width: 600px; margin: 0 auto;">
    <h4 class="alert-heading"><%= @genre.errors.count %> errors occurred</h4>
    <ul>
      <% @genre.errors.full_messages.each do |message| %> 
        <li><%= message %></li>　
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <h1 class="mb-4 text-center">ジャンル管理</h1>

  <% if flash[:success] %>
    <div class="alert alert-success text-center" style="max-width: 600px; margin: 0 auto;">
      <%= flash[:success] %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <%= form_with model: @genre, url: admin_genres_path, class: "form" do |f| %>
        <div class="form-group">
          <label for="genre_name">ジャンル追加</label>
          <%= f.text_field :name, class: "form-control", id: "genre_name", autofocus: true, placeholder: "ジャンル名" %>
        </div>
        <div class="text-left">
          <%= f.submit '追加', class: "btn btn-primary mt-3" %>
        </div>
      <% end %>
    </div>


    <div class="col-md-7 offset-md-1">
      <ul class="list-group">
        <% @genres.each do |genre| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <span>ジャンル名：<%= genre.name %></span>
            <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-secondary btn-sm" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>